package commands

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/datadyne-io/autodoc/internal/doctree"
)

const markerStart = "<!-- autodoc: start -->"
const markerEnd = "<!-- autodoc: end -->"

var agentsPreamble = "## Documentation Index\n\n" +
	"*Auto-generated by `autodoc`. Do not edit manually.*\n\n" +
	"- Run `autodoc quickstart` before first use to learn the workflow.\n" +
	"- Search docs with `autodoc search keyword <query>`.\n" +
	"- Check doc freshness with `autodoc stale`, fix issues with `autodoc fix`.\n" +
	"- Link code to docs with `[autodoc()]` tags — run `autodoc fix` for details.\n\n"

// AgentsWithResult inserts tree output into agent memory files and returns the list of updated files.
func AgentsWithResult(rootDir string, docsDir string, agentFiles []string, ignores []string) ([]string, error) {
	return agentsImpl(rootDir, docsDir, agentFiles, ignores)
}

// AgentsToFile writes the complete doc index to a single specified file,
// bypassing the normal agent-file ownership resolution.
func AgentsToFile(rootDir string, docsDir string, targetFile string, ignores []string) error {
	entries, err := doctree.WalkRepo(rootDir, docsDir, ignores...)
	if err != nil {
		return fmt.Errorf("walking docs: %w", err)
	}

	sort.Slice(entries, func(i, j int) bool {
		return entryDisplayPath(&entries[i]) < entryDisplayPath(&entries[j])
	})

	var buf bytes.Buffer
	DocsIndex(&buf, entries, docsDir)
	block := fmt.Sprintf("%s\n%s%s%s\n", markerStart, agentsPreamble, buf.String(), markerEnd)

	targetAbs := targetFile
	if !filepath.IsAbs(targetAbs) {
		targetAbs = filepath.Join(rootDir, targetFile)
	}

	if _, err := os.Stat(targetAbs); err == nil {
		return updateAgentFile(targetAbs, block)
	}
	if err := os.MkdirAll(filepath.Dir(targetAbs), 0o755); err != nil {
		return fmt.Errorf("creating parent dir for %s: %w", targetFile, err)
	}
	return os.WriteFile(targetAbs, []byte(block), 0o644)
}

// Agents inserts tree output into agent memory files.
func Agents(rootDir string, docsDir string, agentFiles []string, ignores []string) error {
	_, err := agentsImpl(rootDir, docsDir, agentFiles, ignores)
	return err
}

func agentsImpl(rootDir string, docsDir string, agentFiles []string, ignores []string) ([]string, error) {
	if len(agentFiles) == 0 {
		return nil, errors.New("agent files list cannot be empty")
	}

	entries, err := doctree.WalkRepo(rootDir, docsDir, ignores...)
	if err != nil {
		return nil, fmt.Errorf("walking docs: %w", err)
	}

	entriesByOwner := make(map[string][]doctree.Entry)
	ownersToUpdate := make(map[string]struct{})
	for i := range entries {
		entry := &entries[i]
		owners, err := resolveOwnersForDoc(rootDir, filepath.ToSlash(entryDisplayPath(entry)), agentFiles)
		if err != nil {
			return nil, fmt.Errorf("resolve owner for %s: %w", entryDisplayPath(entry), err)
		}
		for _, ownerRel := range owners {
			ownersToUpdate[ownerRel] = struct{}{}
			entriesByOwner[ownerRel] = append(entriesByOwner[ownerRel], *entry)
		}
	}

	if len(ownersToUpdate) == 0 {
		for _, f := range agentFiles {
			pathAbs := filepath.Join(rootDir, filepath.FromSlash(f))
			if _, err := os.Stat(pathAbs); err == nil {
				ownersToUpdate[filepath.ToSlash(f)] = struct{}{}
			}
		}
	}
	if len(ownersToUpdate) == 0 {
		ownersToUpdate[filepath.ToSlash(agentFiles[0])] = struct{}{}
	}

	ownerPaths := make([]string, 0, len(ownersToUpdate))
	for owner := range ownersToUpdate {
		ownerPaths = append(ownerPaths, owner)
	}
	sort.Strings(ownerPaths)

	for _, ownerRel := range ownerPaths {
		group := entriesByOwner[ownerRel]
		sort.Slice(group, func(i, j int) bool {
			return entryDisplayPath(&group[i]) < entryDisplayPath(&group[j])
		})

		var buf bytes.Buffer
		DocsIndex(&buf, group, docsDir)
		indexContent := buf.String()
		block := fmt.Sprintf("%s\n%s%s%s\n", markerStart, agentsPreamble, indexContent, markerEnd)

		ownerAbs := filepath.Join(rootDir, filepath.FromSlash(ownerRel))
		if _, err := os.Stat(ownerAbs); err == nil {
			if err := updateAgentFile(ownerAbs, block); err != nil {
				return nil, fmt.Errorf("updating %s: %w", ownerRel, err)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(ownerAbs), 0o755); err != nil {
			return nil, fmt.Errorf("creating parent dir for %s: %w", ownerRel, err)
		}
		if err := os.WriteFile(ownerAbs, []byte(block), 0o644); err != nil {
			return nil, fmt.Errorf("creating %s: %w", ownerRel, err)
		}
	}

	return ownerPaths, nil
}

func resolveOwnersForDoc(rootDir, docRepoRelPath string, agentFiles []string) ([]string, error) {
	dir := path.Dir(docRepoRelPath)
	if dir == "." {
		dir = ""
	}

	for {
		ownersAtLevel, err := existingOwnersAtDir(rootDir, dir, agentFiles)
		if err != nil {
			return nil, err
		}
		if len(ownersAtLevel) > 0 {
			return ownersAtLevel, nil
		}

		if dir == "" {
			break
		}

		parent := path.Dir(dir)
		if parent == "." {
			parent = ""
		}
		dir = parent
	}

	rootOwners, err := existingOwnersAtDir(rootDir, "", agentFiles)
	if err != nil {
		return nil, err
	}
	if len(rootOwners) > 0 {
		return rootOwners, nil
	}

	return []string{filepath.ToSlash(agentFiles[0])}, nil
}

func existingOwnersAtDir(rootDir, dir string, agentFiles []string) ([]string, error) {
	owners := make([]string, 0, len(agentFiles))
	for _, name := range agentFiles {
		candidate := filepath.ToSlash(name)
		if dir != "" {
			candidate = dir + "/" + filepath.ToSlash(name)
		}

		candidateAbs := filepath.Join(rootDir, filepath.FromSlash(candidate))
		_, err := os.Stat(candidateAbs)
		if err == nil {
			owners = append(owners, candidate)
			continue
		}
		if !os.IsNotExist(err) {
			return nil, err
		}
	}
	return owners, nil
}

func updateAgentFile(path string, block string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	content := string(data)

	startIdx := strings.Index(content, markerStart)
	endIdx := strings.Index(content, markerEnd)

	if startIdx != -1 && endIdx != -1 {
		suffix := content[endIdx+len(markerEnd):]
		trimmedBlock := strings.TrimRight(block, "\n")
		newContent := content[:startIdx] + trimmedBlock + suffix
		return os.WriteFile(path, []byte(newContent), 0o644)
	}

	// Append markers to end
	if !strings.HasSuffix(content, "\n") && len(content) > 0 {
		content += "\n"
	}
	content += "\n" + block
	return os.WriteFile(path, []byte(content), 0o644)
}
