// Package setupscript generates the bash provisioning script emitted by
// `auto artifact setup`. The tool never calls AWS itself — it only prints a
// script the user runs in their own authenticated context.
package setupscript

import (
	"fmt"
	"strings"
)

// Params are the substitutable inputs for the generated script.
type Params struct {
	Region  string
	Bucket  string
	Profile string // optional; empty means "use ambient/instance credentials"
}

// shellSingleQuote wraps s in POSIX single quotes, escaping any embedded single
// quote as '\”. Single-quoted strings undergo no shell expansion, so even a
// value containing $(...) or backticks is emitted as an inert literal — no
// command substitution happens when the user runs the generated script.
func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// Generate returns a self-contained bash script that provisions the artifact
// bucket: bucket creation, public-read/no-list policy, retention lifecycle
// rules, an IAM user (PutObject/DeleteObject) with access keys, and a valid,
// optional IAM role for instance-profile auth (D-6).
func Generate(p Params) string {
	// Values are single-quoted (not Go %q) so shell metacharacters in a bucket,
	// region, or profile are inert literals rather than command substitutions.
	header := fmt.Sprintf(`#!/usr/bin/env bash
set -euo pipefail

# Generated by `+"`auto artifact setup`"+`. Run this in an AWS-authenticated shell.
BUCKET=%s
REGION=%s
PROFILE=%s
IAM_USER="auto-artifact-uploader"
IAM_ROLE="auto-artifact-role"
IAM_POLICY="auto-artifact-policy"
`, shellSingleQuote(p.Bucket), shellSingleQuote(p.Region), shellSingleQuote(p.Profile))

	return header + scriptBody
}

// scriptBody is the static remainder of the script. It references the bash
// variables set in the header, so only the header is parameterized.
const scriptBody = `
# run_aws wraps the AWS CLI, appending --profile only when one is configured.
run_aws() {
  if [[ -n "$PROFILE" ]]; then
    aws "$@" --profile "$PROFILE"
  else
    aws "$@"
  fi
}

ACCOUNT_ID=$(run_aws sts get-caller-identity --query Account --output text)

echo "=== Auto Artifact AWS Setup ==="
echo "Bucket:  $BUCKET"
echo "Region:  $REGION"
echo "Account: $ACCOUNT_ID"
echo ""

# --- 1. Create S3 bucket (us-east-1 must omit LocationConstraint) ---
echo "[1/7] Creating S3 bucket..."
if [[ "$REGION" == "us-east-1" ]]; then
  run_aws s3api create-bucket --bucket "$BUCKET" --region "$REGION"
else
  run_aws s3api create-bucket \
    --bucket "$BUCKET" \
    --region "$REGION" \
    --create-bucket-configuration LocationConstraint="$REGION"
fi

# --- 2. Block public ACLs but allow a public bucket policy ---
echo "[2/7] Configuring public access settings..."
run_aws s3api put-public-access-block \
  --bucket "$BUCKET" \
  --public-access-block-configuration \
    'BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=false,RestrictPublicBuckets=false'

# --- 3. Bucket policy: public GetObject, deny ListBucket ---
echo "[3/7] Setting bucket policy (public read, no list)..."
run_aws s3api put-bucket-policy \
  --bucket "$BUCKET" \
  --policy "$(cat <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "PublicReadGetObject",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::${BUCKET}/*"
    },
    {
      "Sid": "DenyListBucket",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:ListBucket",
      "Resource": "arn:aws:s3:::${BUCKET}"
    }
  ]
}
POLICY
)"

# --- 4. Lifecycle rules for retention prefixes ---
echo "[4/7] Setting lifecycle rules (7d, 30d, 90d, 365d)..."
run_aws s3api put-bucket-lifecycle-configuration \
  --bucket "$BUCKET" \
  --lifecycle-configuration "$(cat <<LIFECYCLE
{
  "Rules": [
    { "ID": "expire-7d",   "Filter": { "Prefix": "7d/" },   "Status": "Enabled", "Expiration": { "Days": 7 } },
    { "ID": "expire-30d",  "Filter": { "Prefix": "30d/" },  "Status": "Enabled", "Expiration": { "Days": 30 } },
    { "ID": "expire-90d",  "Filter": { "Prefix": "90d/" },  "Status": "Enabled", "Expiration": { "Days": 90 } },
    { "ID": "expire-365d", "Filter": { "Prefix": "365d/" }, "Status": "Enabled", "Expiration": { "Days": 365 } }
  ]
}
LIFECYCLE
)"

# --- 5. IAM policy (PutObject/DeleteObject only) ---
echo "[5/7] Creating IAM policy..."
POLICY_ARN=$(run_aws iam create-policy \
  --policy-name "$IAM_POLICY" \
  --policy-document "$(cat <<IAMPOLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "ArtifactUploadDelete",
      "Effect": "Allow",
      "Action": [ "s3:PutObject", "s3:DeleteObject" ],
      "Resource": "arn:aws:s3:::${BUCKET}/*"
    }
  ]
}
IAMPOLICY
)" \
  --query 'Policy.Arn' --output text)
echo "  Policy ARN: $POLICY_ARN"

# --- 6. IAM user (static keys) + IAM role (optional instance-profile auth) ---
echo "[6/7] Creating IAM user and role..."
run_aws iam create-user --user-name "$IAM_USER"
run_aws iam attach-user-policy --user-name "$IAM_USER" --policy-arn "$POLICY_ARN"

# A genuinely usable role: agents on EC2/ECS can assume it and upload without
# static keys. v1's CLI authenticates with the IAM user + access keys below;
# the role is an optional extra (D-6).
run_aws iam create-role \
  --role-name "$IAM_ROLE" \
  --assume-role-policy-document "$(cat <<TRUST
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": { "Service": [ "ec2.amazonaws.com", "ecs-tasks.amazonaws.com" ] },
      "Action": "sts:AssumeRole"
    }
  ]
}
TRUST
)"
run_aws iam attach-role-policy --role-name "$IAM_ROLE" --policy-arn "$POLICY_ARN"

# --- 7. Access keys for the IAM user ---
echo "[7/7] Creating access keys..."
KEYS=$(run_aws iam create-access-key \
  --user-name "$IAM_USER" \
  --query 'AccessKey.[AccessKeyId,SecretAccessKey]' --output text)
ACCESS_KEY_ID=$(echo "$KEYS" | awk '{print $1}')
SECRET_ACCESS_KEY=$(echo "$KEYS" | awk '{print $2}')

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Run this to configure auto artifact:"
echo ""
echo "  auto artifact init \\"
echo "    --endpoint \"https://s3.${REGION}.amazonaws.com\" \\"
echo "    --bucket \"${BUCKET}\" \\"
echo "    --region \"${REGION}\" \\"
echo "    --access-key-id \"${ACCESS_KEY_ID}\" \\"
echo "    --secret-access-key \"${SECRET_ACCESS_KEY}\""
echo ""
echo "Artifact URLs will be:"
echo "  https://${BUCKET}.s3.${REGION}.amazonaws.com/{retention}/{uuid}/{filename}"
echo ""
echo "IMPORTANT: Save the secret access key above — it cannot be retrieved again."
`
