server {
    listen 443 ssl default_server;
    server_name git-server;

    ssl_certificate     /certs/server.crt;
    ssl_certificate_key /certs/server.key;

    location ~ ^/repos/(.*)$ {
        client_max_body_size 0;
        fastcgi_param SCRIPT_FILENAME /usr/libexec/git-core/git-http-backend;
        include fastcgi_params;
        fastcgi_param GIT_HTTP_EXPORT_ALL "";
        fastcgi_param GIT_PROJECT_ROOT /repos;
        fastcgi_param PATH_INFO /$1;
        fastcgi_pass unix:/run/fcgiwrap.sock;
    }
}
